/*
 * This file was automatically generated by oml2-scaffold V2.11.0
 * for virtual-server version 1.0.0.
 * 
 */

#define PACKAGE			"virtual-server"
#define VERSION			"1.0.0"

/* Provide compatibility with autoconf-generated config.h */
#define PACKAGE_NAME		PACKAGE
#define PACKAGE_TAR_NAME	PACKAGE
#define PACKAGE_VERSION		VERSION

