# This file was automatically generated by oml2-scaffold V2.10.0
# The syntax of this file is documented at [0].
#
# [0] http://doc.mytestbed.net/doc/omf/OmfEc/Backward/AppDefinition.html

defApplication('wontoniii:app:virtual-server', 'virtual-server') do |app|

  app.version(1, 0, 0)
  app.shortDescription = 'Virtual Server for VN-ASR demo'
  app.description = %{
  Virtual Server for Virtual Network - Application Specific Routing demo
}
  app.path = "/root/apps/virtual-server"

  # Declare command-line arguments; generate Popt parser with
  #  oml2-scaffold --opts mfandroidstack.rb

  # Example of a command-line argument types; see popt(3) for more details
  #  app.defProperty('double_var', 'Command line option of type double', '--double',
  #        :type => :double, :var_name => 'vardouble')


  # Declare measurement points; generate OML injection helpers with
  #  oml2-scaffold --oml mfandroidstack.rb
  app.defMeasurement("app_metrics") do |mp|
	mp.defMetric('GUID', :string)
	mp.defMetric('load', :double)
  end

end

# Local Variables:
# mode:ruby
# End:
# vim: ft=ruby:sw=2
